# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Get latest CMake
      # Using 'latest' branch, the latest CMake is installed.
      uses: lukka/get-cmake@latest

    # Restore from cache the previously built ports. If "cache miss", then provision vcpkg, install desired ports, finally cache everything for the next run.
    - name: Restore from cache and run vcpkg
      uses: lukka/run-vcpkg@v3
      with:
        # Response file stored in source control, it provides the list of ports and triplet(s).
        vcpkgArguments: '@${{ github.workspace }}/vcpkg_win.txt'
        # Location of the vcpkg as submodule of the repository.
        vcpkgDirectory: '${{ github.workspace }}/vendor/vcpkg'
        # Since the cache must be invalidated when content of the response file changes, let's
        # compute its hash and append this to the computed cache's key.
        appendedCacheKey: ${{ hashFiles('vcpkg_win.txt') }}

    # Build the overlay for 32-bit
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86
    - name: Build Overlay (32-bit Debug)
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_C_COMPILER:PATH="cl.exe" -DCMAKE_CXX_COMPILER:PATH="cl.exe" '
        buildDirectory: ${{ runner.temp }}/build/x86
        buildWithCMake: true
    - name: Build Overlay (32-bit Release)
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_C_COMPILER:PATH="cl.exe" -DCMAKE_CXX_COMPILER:PATH="cl.exe" '
        buildDirectory: ${{ runner.temp }}/build/x86
        buildWithCMake: true

    # Build the overlay for 64-bit
    - uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build Overlay (64-bit Debug)
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_C_COMPILER:PATH="cl.exe" -DCMAKE_CXX_COMPILER:PATH="cl.exe" '
        buildDirectory: ${{ runner.temp }}/build/x64
        buildWithCMake: true
    - name: Build Overlay (64-bit Release)
      uses: lukka/run-cmake@v2
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
        cmakeAppendedArgs: '-GNinja -DCMAKE_BUILD_TYPE=Release -DVCPKG_TARGET_TRIPLET=x64-windows-static -DCMAKE_C_COMPILER:PATH="cl.exe" -DCMAKE_CXX_COMPILER:PATH="cl.exe" '
        buildDirectory: ${{ runner.temp }}/build/x64
        buildWithCMake: true

    # Save built overlay
    - name: Save x86 debug build
      uses: actions/upload-artifact@v2
      with:
        name: overlay-x86-debug
        path: ${{ github.workspace }}/bin/x86/debug
    - name: Save x86 release build
      uses: actions/upload-artifact@v2
      with:
        name: overlay-x86-release
        path: ${{ github.workspace }}/bin/x86/release
    - name: Save x64 debug build
      uses: actions/upload-artifact@v2
      with:
        name: overlay-x64-debug
        path: ${{ github.workspace }}/bin/x64/debug
    - name: Save x64 release build
      uses: actions/upload-artifact@v2
      with:
        name: overlay-x64-release
        path: ${{ github.workspace }}/bin/x64/release